trash 0.7.1

diff --git a/bin/trash b/bin/trash
--- a/bin/trash
+++ b/bin/trash
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-#
+# 
 # trash - Move files to the appropriate .Trash file on Mac OS X. (Intended
 #         as an alternative to 'rm' which immediately deletes the file.)
-#
+# 
 # v0.1   2007-05-21 - Morgan Aldridge <morgant@makkintosshu.com>
 #                     Initial version.
 # v0.2   2010-10-26 - Morgan Aldridge
@@ -32,6 +32,14 @@
 #                     Also correctly warns of missing files/directories.
 # v0.5.3 2013-08-23 - huyz
 #                     Fixed determination of Finder's PID when Path Finder is running
+# v0.6   2014-01-30 - Lucas Morales
+#                     Added long argument forms.
+# v0.6.1 2014-05-12 - Matt Torok
+#                     Supress `osascript` output when moving files to trash.
+# v0.7   2021-02-26 - Morgan Aldridge
+#                     Check for Full Disk Access on macOS >= 10.15.
+# v0.7.1 2021-04-09 - Morgan Aldridge
+#                     Improved Full Disk Access instructions.
 #
 
 # global variables
@@ -44,10 +52,20 @@ v=''
 # print usage instructions (help)
 function usage() {
 	printf "Usage: trash [options] file ...\n"
-	printf "  -v		verbose output\n"
-	printf "  -h		print these usage instructions\n"
-	printf "  -l            list trash contents\n"
-	printf "  -e            empty trash contents\n"
+	printf "  -v --verbose   verbose output\n"
+	printf "  -h --help      print these usage instructions\n"
+	printf "  -l --list      list trash contents\n"
+	printf "  -e --empty     empty trash contents\n"
+	printf "  -s --sempty    secure empty trash contents\n"
+}
+
+# determine whether we have full disk access
+function have_full_disk_access() {
+  if [ $(sw_vers -productVersion | cut -d . -f 1) -lt 11 ] && [ $(sw_vers -productVersion | cut -d . -f 2) -lt 15 ] ; then
+    true
+  else
+    sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db 'select * from access' > /dev/null 2>&1 && true || false
+  fi
 }
 
 # determine whether we can script the Finder or not
@@ -60,95 +78,104 @@ function have_scriptable_finder() {
 	fi
 }
 
-##
+## 
 ## Convert a relative path to an absolute path.
-##
+## 
 ## From http://github.com/morgant/realpath
-##
+## 
 ## @param string the string to converted from a relative path to an absolute path
 ## @returns Outputs the absolute path to STDOUT, returns 0 if successful or 1 if an error (esp. path not found).
-##
+## 
 function realpath()
 {
 	local success=true
 	local path="$1"
-
+	
 	# make sure the string isn't empty as that implies something in further logic
 	if [ -z "$path" ]; then
 		success=false
 	else
 		# start with the file name (sans the trailing slash)
 		path="${path%/}"
-
+		
 		# if we stripped off the trailing slash and were left with nothing, that means we're in the root directory
 		if [ -z "$path" ]; then
 			path="/"
 		fi
-
+		
 		# get the basename of the file (ignoring '.' & '..', because they're really part of the path)
 		local file_basename="${path##*/}"
 		if [[ ( "$file_basename" = "." ) || ( "$file_basename" = ".." ) ]]; then
 			file_basename=""
 		fi
-
+		
 		# extracts the directory component of the full path, if it's empty then assume '.' (the current working directory)
 		local directory="${path%$file_basename}"
 		if [ -z "$directory" ]; then
 			directory='.'
 		fi
-
+		
 		# attempt to change to the directory
 		if ! cd "$directory" &>/dev/null ; then
 			success=false
 		fi
-
+		
 		if $success; then
 			# does the filename exist?
 			if [[ ( -n "$file_basename" ) && ( ! -e "$file_basename" ) ]]; then
 				success=false
 			fi
-
+			
 			# get the absolute path of the current directory & change back to previous directory
 			local abs_path="$(pwd -P)"
 			cd "-" &>/dev/null
-
+			  
 			# Append base filename to absolute path
 			if [ "${abs_path}" = "/" ]; then
 				abs_path="${abs_path}${file_basename}"
 			else
 				abs_path="${abs_path}/${file_basename}"
 			fi
-
+			
 			# output the absolute path
 			echo "$abs_path"
 		fi
 	fi
-
+	
 	$success
 }
+
+if ! have_full_disk_access ; then
+  printf "%s requires Full Disk Access!\n\n" "$(basename "$0")"
+  printf "Please go to System Preferences > Security & Privacy > Privacy > Full Disk Access,\n"
+  printf "press the '+' button, and add:\n\n"
+  printf "1. Your terminal application (usually /Applications/Utilities/Terminal.app)\n"
+  printf "2. /usr/libexec/sshd-keygen-wrapper (if you plan to connect via SSH)\n"
+  exit 1
+fi
 
 # see if any arguments were passed in
 if [ $# -gt 0 ]; then
 	# if so, step through them all and process them
 	while [ $# -gt 0 ]; do
 		# see if the user intended us to run in verbose mode
-		if [ "$1" = "-v" ]; then
+		if [ "$1" = "-v" ] || [ "$1" = "--verbose" ]; then
 			shift
 			verbose=true
 		# see if the user requested help
-		elif [ "$1" = "-h" ]; then
+		elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 			shift
 			usage
 			exit
 		# see if the user requested a list of trash contents
-		elif [ "$1" = "-l" ]; then
+		elif [ "$1" = "-l" ] || [ "$1" = "--list" ]; then
 			shift
 			num_volumes=0
 			total_blocks=0
 			# list file contents & calculate size for user's .Trash folder
-			if find "${HOME}/.Trash" -mindepth 1; then
+			if find "/Users/${user}/.Trash" -depth 1 ! -depth 0; then
 				num_volumes=$(( $num_volumes + 1 ))
-				blocks=$(du -cs "${HOME}/.Trash" | tail -n 1 | cut -f 1)
+				blocks=$(du -cs "/Users/${user}/.Trash" | tail -n 1 | cut -f 1)
 				total_blocks=$(( $total_blocks + $blocks ))
 			fi
 			# list file contents & calculate size for volume-specific .Trashes folders
@@ -179,7 +206,7 @@ if [ $# -gt 0 ]; then
 			printf "%s across %s volume(s).\n" "$size" $num_volumes
 			exit
 		# see if the user requested to empty the trash contents
-		elif [ "$1" = "-e" ]; then
+		elif [ "$1" = "-e" ] || [ "$1" = "--empty" ]; then
 			shift
 			# determine if we can tell Finder to empty trash via AppleScript
 			if have_scriptable_finder; then
@@ -200,7 +227,7 @@ if [ $# -gt 0 ]; then
 				if [ "$confirm" = "y" ]; then
 					printf "Emptying trash...\n"
 					# delete the contents of user's .Trash folder
-					find "${HOME}/.Trash" -mindepth 1 -print0 | xargs -0 rm $v -r
+					find "/Users/${user}/.Trash" -depth 1 ! -depth 0 -print0 | xargs -0 rm $v -r
 					# delete the contents of the volume-specific .Trashes folders
 					for file in /Volumes/*; do
 						if [ -d "$file" ]; then
@@ -214,12 +241,48 @@ if [ $# -gt 0 ]; then
 				fi
 				exit
 			fi
+		# see if the user requested to securely empty the trash contents
+		elif [ "$1" = "-s" ] || [ "$1" = "--sempty" ]; then
+			shift
+			# determine if we can tell Finder to securely empty trash via AppleScript
+			if have_scriptable_finder; then
+				if $verbose; then printf "Telling Finder to securely empty trash... "; fi
+				if /usr/bin/osascript -e "tell application \"Finder\" to empty trash with security" ; then
+					if $verbose; then printf "Done.\n"; fi
+					exit
+				else
+					if $verbose; then printf "ERROR!\n"; fi
+					exit 1
+				fi
+			# if Finder isn't scriptable, we'll manually empty the trash ourselves
+			else
+				if $verbose; then v="-v"; fi
+				# confirm that the user wants to securely empty the trash
+				printf "Are you sure you want to securely empty the trash (this REALLY cannot be undone)? "
+				read confirm
+				if [ "$confirm" = "y" ]; then
+					printf "Securely emptying trash...\n"
+					# securely delete the contents of user's .Trash folder
+					find "/Users/${user}/.Trash" -depth 1 ! -depth 0 -print0 | xargs -0 srm $v -r
+					# securely delete the contents of the volume-specific .Trashes folders
+					for file in /Volumes/*; do
+						if [ -d "$file" ]; then
+							folder="${file}/.Trashes/${uid}"
+							if [ -d "$folder" ]; then
+								find "$folder" -depth 1 ! -depth 0 -print0 | xargs -0 srm $v -r
+							fi
+						fi
+					done
+					printf "Done.\n"
+				fi
+				exit
+			fi
 		# handle remaining arguments as if they were files
 		else
 			#printf "argument: '%s'\n" $1
 			#printf "destination: '%s'\n" $TRASH
 			if $verbose; then v="-v"; fi
-
+			
 			# does the file we're trashing exist?
 			if [ ! -e "$1" ]; then
 				printf "trash: '%s': No such file or directory\n" "$1"
@@ -241,7 +304,7 @@ if [ $# -gt 0 ]; then
 						fi
 					fi
 					if $verbose; then printf "Telling Finder to trash '%s'... " "$file"; fi
-					if /usr/bin/osascript -e "tell application \"Finder\" to delete POSIX file \"$file\"" ; then
+					if /usr/bin/osascript -e "tell application \"Finder\" to delete POSIX file \"$file\"" >/dev/null ; then
 						if $verbose; then printf "Done.\n"; fi
 					else
 						if $verbose; then printf "ERROR!\n"; fi
@@ -253,7 +316,7 @@ if [ $# -gt 0 ]; then
 					if [[ ("${1:0:9}" == "/Volumes/") && (-n "$vol") && ($(readlink "/Volumes/$vol") != "/") ]]; then
 						trash="/Volumes/${vol}/.Trashes/${uid}/"
 					else
-						trash="${HOME}/.Trash/"
+						trash="/Users/${user}/.Trash/"
 					fi
 					# create the trash folder if necessary
 					if [ ! -d "$trash" ]; then
@@ -268,7 +331,7 @@ if [ $# -gt 0 ]; then
 						case "$1" in
 							*.*) ext=true ;;
 						esac
-
+						
 						# keep incrementing a number to append to the filename to mimic Finder
 						i=1
 						if $ext; then
@@ -284,7 +347,7 @@ if [ $# -gt 0 ]; then
 								new="${trash}$1 $i"
 							fi
 						done
-
+						
 						#move the file to the trash with the new name
 						mv $v "$1" "$new"
 					fi
